### ISSUE TITLE
AnimatedSprite blinking between old colour and swapped colour

### ISSUE THREAD

**Issue by jtbx** [KoBeWi/Godot-Palette-Swap-Shader#1]
My AnimatedSprite node is blinking between the old appearance and the new palette swapped appearance every 1-1.5 seconds. The shader is inside the `shader` property of the resource, and turning the FPS up makes it blink faster.

**Comment by KoBeWi** [comment]
What Godot version are you using?
Did you enable `skip_first_row`?

**Comment by jtbx** [comment]
I'm using Godot version 3.5.1 stable. Enabling or disabling skip_first_row​ doesn't really change anything.
------- Original Message -------

**Comment by jtbx** [comment]
I'm using Godot version 3.5.1 stable. Enabling or disabling skip_first_row​ doesn't really change anything.

**Comment by KoBeWi** [comment]
Did you disable `filter` on both palette and the recolored image?

I can't reproduce it. Can you attach some example scene with this issue?

**Comment by jtbx** [comment]
I have disabled filter on both images.
[demo.zip](https://github.com/KoBeWi/Godot-Palette-Swap-Shader/files/10440797/demo.zip)

**Comment by KoBeWi** [comment]
Your palette is too big. Each row/column of the palette should be 1px. It works when you scale `none.png` down 10 times (to 1x2).

**Comment by jtbx** [comment]
Thanks!
