### ISSUE TITLE
What if I wanted to use it in code?

### ISSUE THREAD

**Issue by LitttlePigGames** [KoBeWi/Godot-Palette-Swap-Shader#12]
I want to change color palettes mid-game but I can't find code that works

`$AnimatedSprite2D.shader_parameter/palette = load("res://emptypallete.png")` won't work due to "shader_parameter/palette" giving the issue "Only identifier, attribute access, and subscription access can be used as assignment target."

**Comment by KoBeWi** [comment]
`$AnimatedSprite2D.material.set_shader_parameter("palette", load("res://emptypallete.png"))`
