### ISSUE TITLE
Compatibility with Godot 4.2

### ISSUE THREAD

**Issue by ScribblerJones** [KoBeWi/Godot-Palette-Swap-Shader#8]
I opened the example demo in Godot 4.2, but it did not look like the gif image in the readme that showed how to select and input the palette. I don't see a section designated "Shader Param" like the one in the gif, nor do I see a slot where you can drag over the desired palette for your sprite. There is nothing for "fps" or "palette." 

I tested it out in Godot 3 and it seems to work just fine. It just does not work in Godot 4 for me.

**Comment by ScribblerJones** [comment]
Edit: I played around and noticed that the script section for the shader in Godot 4 only had a reference to the path where the shader is stored in the project... so I went into Godot 3, where it has the full shader code typed out, copied it from there and pasted it into the Godot 4 version. The demo works now. If this is what I should have done from the start, I apologize for any misunderstanding. I did not know if I had simply overlooked something or if something was genuinely wrong.

**Comment by KoBeWi** [comment]
It's a bug. I used symlinks to avoid duplicating files, but they seem unreliable.

**Comment by KoBeWi** [comment]
Should be fixed by a3c87c02833f311124a71ba8715823fb225dbe9d
Try downloading again.

**Comment by ScribblerJones** [comment]
It works properly now. Thank you - and once again, I apologize for any inconvenience.
